### PR TITLE
add downloadble pkpass file to apple wallet

### PR DESCRIPTION
**Pull request by Tosin-Balogun**
## Description
Add downloadable pkpass file to simulate prescription barcode apple wallet feature
## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] CHANGELOG entry

### CODE REVIEW

**Review by edwardscull — CHANGES_REQUESTED** [review]
The `package-lock.json` file shouldn't of been changed here. Could you revert it and push again?

**Comment by Tosin-Balogun** [comment]
> The `package-lock.json` file shouldn't of been changed here. Could you revert it and push again?

I didn't touch the package file. Are you able to show me what you mean?

**Comment by edwardscull** [comment]
> > The `package-lock.json` file shouldn't of been changed here. Could you revert it and push again?
> 
> I didn't touch the package file. Are you able to show me what you mean?
> 
> @edwardscull I have just seen that you updated the json package file. How do I revert? Do I pull this branch and push again or?

I assume you ran `npm install` at some point? This has changed the `package-lock` file for some reason. It shouldn't get changed but this won't be due to anything you did I am assuming.

If you roll back your commit and make your change to just the template and then run `npm ci` instead. The `package-lock` file should not get changed and then you can push again to this PR.

**Comment by Tosin-Balogun** [comment]
> > > The `package-lock.json` file shouldn't of been changed here. Could you revert it and push again?
> > 
> > 
> > I didn't touch the package file. Are you able to show me what you mean?
> > @edwardscull I have just seen that you updated the json package file. How do I revert? Do I pull this branch and push again or?
> 
> I assume you ran `npm install` at some point? This has changed the `package-lock` file for some reason. It shouldn't get changed but this won't be due to anything you did I am assuming.
> 
> If you roll back your commit and make your change to just the template and then run `npm ci` instead. The `package-lock` file should not get changed and then you can push again to this PR.

Thanks @edwardscull :) 

I have tried to undo the commit, run the `npm ci` and re-did the commit. Does that work?

**Comment by edwardscull** [comment]
@Tosin-Balogun your latest commit shows no difference to the previous commit? If you're unsure have a look here https://stackoverflow.com/questions/15772134/can-i-delete-a-git-commit-but-keep-the-changes. Or you could
- close this pull request
- make a brand new branch from develop
- make your changes
- run `npm ci` and revert the `package-lock.json` file only IF it shows there are changes made to it
- then push your new branch and make a new PR

**Comment by Tosin-Balogun** [comment]
Closing the branch as advised. Will create new branch and run the commands

**Comment by Tosin-Balogun** [comment]
> @Tosin-Balogun your latest commit shows no difference to the previous commit? If you're unsure have a look here https://stackoverflow.com/questions/15772134/can-i-delete-a-git-commit-but-keep-the-changes. Or you could
> 
> * close this pull request
> * make a brand new branch from develop
> * make your changes
> * run `npm ci` and revert the `package-lock.json` file only IF it shows there are changes made to it
> * then push your new branch and make a new PR

@edwardscull thanks. I have closed the commit.

Running through the steps. I got to the bit where i'm running the npm ci again, but it throws up an error

```
tosin@Tosins-MBP nhs-app-design-styles-components-patterns % npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Cannot read property '@babel/core' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tosin/.npm/_logs/2024-08-12T12_34_54_217Z-debug.log
tosin@Tosins-MBP nhs-app-design-styles-components-patterns % npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Cannot read property '@babel/core' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tosin/.npm/_logs/2024-08-12T12_37_55_859Z-debug.log

```
Do you know what might be the reason?

**Comment by edwardscull** [comment]
@Tosin-Balogun did you ensure you had pulled the latest `main` before you started working? If you
- stash your local changes on your current working branch (https://git-scm.com/docs/git-stash)
- checkout `main` and run `git pull`. What happens? Does it say "already up to date"? Or does it pull new code?
- checkout a new branch from `main` and apply your stashed changes to this new branch. Everything should now be running off of the latest
- run `npm install` should now no longer change the `package-lock.json` file
- delete old branches that are not needed anymore

**Comment by Tosin-Balogun** [comment]
> @Tosin-Balogun did you ensure you had pulled the latest `main` before you started working? If you
> 
> * stash your local changes on your current working branch (https://git-scm.com/docs/git-stash)
> * checkout `main` and run `git pull`. What happens? Does it say "already up to date"? Or does it pull new code?
> * checkout a new branch from `main` and apply your stashed changes to this new branch. Everything should now be running off of the latest
> * run `npm install` should now no longer change the `package-lock.json` file
> * delete old branches that are not needed anymore

@edwardscull so when I went to the main branch to run a pull, it was already up to date. The I did an `npm install` and it showed the json package file has changes.

Do I discard the changes?

Screenshot 2024-08-12 at 14 03 54

**Comment by edwardscull** [comment]
@Tosin-Balogun yes discard those changes before pushing 👍

**Comment by Tosin-Balogun** [comment]
> @Tosin-Balogun yes discard those changes before pushing 👍

I have opened a new PR here https://github.com/nhsuk/nhs-app-design-styles-components-patterns/pull/83

**Pull request closed without merging**
